# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egreeting.proto\"c\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"d\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x17\n\x06status\x18\x03 \x01(\x0e\x32\x07.StatusB\t\n\x07objects\"l\n\rCreateRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\x05genre\x18\x04 \x01(\x0e\x32\x06.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"!\n\x0e\x43reateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1a\n\nGetRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t*3\n\x05Genre\x12\x0e\n\nHISTORICAL\x10\x00\x12\r\n\tADVENTURE\x10\x01\x12\x0b\n\x07ROMANCE\x10\x02*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32\x64\n\x10InventoryService\x12/\n\nCreateBook\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\"\x00\x12\x1f\n\x07GetBook\x12\x0b.GetRequest\x1a\x05.Book\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=394
  _GENRE._serialized_end=445
  _STATUS._serialized_start=447
  _STATUS._serialized_end=481
  _BOOK._serialized_start=18
  _BOOK._serialized_end=117
  _INVENTORYITEM._serialized_start=119
  _INVENTORYITEM._serialized_end=219
  _CREATEREQUEST._serialized_start=221
  _CREATEREQUEST._serialized_end=329
  _CREATERESPONSE._serialized_start=331
  _CREATERESPONSE._serialized_end=364
  _GETREQUEST._serialized_start=366
  _GETREQUEST._serialized_end=392
  _INVENTORYSERVICE._serialized_start=483
  _INVENTORYSERVICE._serialized_end=583
# @@protoc_insertion_point(module_scope)
